### ISSUE TITLE
In v-infinite-scroll, the browser becomes very laggy.

### ISSUE THREAD

**Issue by xiaoxuwei12345** [DerYeger/yeger#309]
### Description

I want to use @ yeger/vue masonry wall in v-infinite-scroll, but I find that after scrolling a few pages, the browser becomes very laggy. Does @ yeger/vue masonry wall not support use in v-infinite-scroll?

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
`@yeger/vue-masonry-wall` is not designed to support any specific other library. I haven't worked with v-infinite-scroll myself, but if it's constantly resizing the container of the masonry component or changing/adding new items the performance will degrade. This could occur when v-infinite-scroll triggers the fetching of new items unexpectedly during the rerender of the masonry wall (because that requires recreating all elements, thus making the wall empty for a single Vue-tick).

**Comment by xiaoxuwei12345** [comment]
Thank you for your reply! When I use v-infinity scroll, when the element content increases to around 200, it will be very slow (every time 30 new elements are added, the page will freeze for more than 3 seconds). I think infinite scrolling is a very common requirement when using MasonryWall (or other similar Masonry or Grid components). What library do you recommend combining MasonryWall with for infinite scrolling? thank you!

**Comment by DerYeger** [comment]
I can’t recommend a specific library, since I haven’t had that use case myself.
